### ISSUE TITLE
Update for docker container 

### ISSUE THREAD

**Issue by engageub** [jepbura/gaganode#1]
Hi @jepbura,
Thank you for creating repository and docker node for gaganode.
I tried to use docker pull but the it shows manifest unknown.
Could you please update the app in docker hub platform.

https://hub.docker.com/r/jepbura/gaganode

Thank you

**Comment by jepbura** [comment]
Hi @engageub,
The problem is solved.
You can use [jepbura/gaganode:2](https://hub.docker.com/r/jepbura/gaganode/tags) version 2.

**Comment by engageub** [comment]
Hi @jepbura,
Thank you for the update. I see your code supports arm64 architecture. Could you please add that to docker also.
From the list of tags I only see amd64. 

https://hub.docker.com/r/jepbura/gaganode/tags

Thank you

**Comment by engageub** [comment]
I tried to do docker pull but the access is denied. 
The error shows "**`pull access denied for jebpura/gaganode, repository does not exist or may require 'docker login': denied:   request access to the resource is denied`**".
Could you please provide permissions in dockerhub for public access.

Thank you

**Comment by jepbura** [comment]
@engageub 
You should have used the following command:
`docker pull jebpura/gaganode:2`
But in any case, I made it this way now
`docker pull jebpura/gaganode`
So it doesn't matter which one you use.

**Comment by jepbura** [comment]
@engageub 
In the meantime, I check the type of CPU model with the following commands:
`if [ "${cpu_arch}" = "x86_64" ]; then
DOWNLOADLINK=$AMD
FILENAME="app-linux-amd64.tar.gz"
elif [[ "${cpu_arch}" = "arm64" ]] || [[ "${cpu_arch}" = "aarch64" ]]; then
DOWNLOADLINK=$ARM
FILENAME="app-linux-arm64.tar.gz"
else
echo "Your CPU type dose not support" 
exit 1
fi`
that x86_64 is for amd64's model.

**Comment by engageub** [comment]
@jepbura,
Thank you for the update. The latest version is working fine for amd64. I see the node online.
Could you please update architecture in docker for arm64 also. 
https://hub.docker.com/r/jepbura/gaganode/tags

Thank you

**Comment by jepbura** [comment]
@engageub 
Solved,
Use `docker pull jepbura/gaganode:arm64` for arm64.
And use `docker pull jepbura/gaganode:amd64` for amd64.

**Comment by engageub** [comment]
@jepbura ,
Thank you for the update.
Could you please update meson nodes also similarly. The last update was 5 months back and it has the same problem. 
https://hub.docker.com/r/jepbura/meson/tags

Thank you

**Comment by jepbura** [comment]
@engageub
Solved,
Use `docker pull jepbura/meson:arm64` for arm64.
And use `docker pull jepbura/meson:amd64` for amd64.

But because I don't have an active server, I couldn't test it.

**Comment by engageub** [comment]
Thank you for the update.
Meson node was not showing online. I tried it in the following website. gaganode works fine.
 https://labs.play-with-docker.com/

The logs don't show any errors.

If you want to test docker, you may use the following. It resets every ~4 hours. 
https://labs.play-with-docker.com/

**Comment by jepbura** [comment]
@engageub 
It's interesting,
I can't even run Meson on a server without docker.
I wrote this Dockerfile a few months ago.
Unfortunately, it doesn't work now

**Comment by jepbura** [comment]
@engageub 
It ran without any problems for me.
![Screenshot 2023-05-21 193206](https://github.com/jepbura/gaganode/assets/25738325/f57f330b-2e74-41dd-9ce1-869bdcb6963f)

Just note that the port you choose in **ENV** must be kept open at the same time:
`docker run -d -p 9222:9222 -e TOKEN=xxxxxxxxx -e PORT=9222 --name meson jepbura/meson:latest`
And that it takes a while for Node to appear in [user_node](https://dashboard.meson.network/user_node).

**Comment by engageub** [comment]
Thank you for the response. Could you please update this in your instructions also. If space or cache-size is variable, could you please add this variable as part of environment variable instead of hardcoding it in the script. This will let users to set the size based on the availability of diskspace. 
Keeping the default value if nothing is specified for cache-size will be fine.
If possible can mount point to specified for the cache size allocation before the container starts. This is to ensure there is no data loss when containers are deleted.

Thank you

**Comment by jepbura** [comment]
@engageub 
I added CACHE_SIZE to Meson's docker image.

[jepbura/meson](https://github.com/jepbura/meson)
