### ISSUE TITLE
[Docker] [Gaganode]Shebang line for arm64 architecture

### ISSUE THREAD

**Issue by engageub** [jepbura/gaganode#2]
Hi,
I ran the container in arm64 architecture and it fails to start with the following error. After changing the shebang line from /bin/sh to /bin/bash it started working.
Could you please make this change and push the code. 
```
cpu_arch=aarch64
Your CPU type dose not support
./gaganode_install.sh: 11: [[: not found
./gaganode_install.sh: 11: [[: not found
```

Thank you

**Comment by engageub** [comment]
In addition to the above, could you please add arm64 in the latest tag instead of separate tag.
For example, the following has different OS architectures in same tag latest. 
https://hub.docker.com/r/xjasonlyu/tun2socks/tags
This will automatically detect the OS architecture and download.

Thank you

**Comment by engageub** [comment]
@jepbura,

Gentle Reminder,
Could you please update on this.
If possible, could you please publish the package to github repository so that it can be pulled from github directly instead of  docker.
This will be added to the code of InternetIncome script once the changes are made. 

Example: https://github.com/xjasonlyu/tun2socks/pkgs/container/tun2socks 

Thank you

**Comment by ElDavoo** [comment]
@jepbura ?

**Comment by engageub** [comment]
@jepbura,

Meson Token is listed in many exchanges and trading is going to commence on April 29th of this month.
I see that code changes are made in github but not published in docker.
Could you please publish the package in github or docker. 

Thank you

**Comment by jepbura** [comment]
@engageub @ElDavoo 
I made a new version of gaganode, I hope it solves your problem.

**Comment by engageub** [comment]
@jepbura 
Thank you for the update.
