### ISSUE TITLE
Errors in docker logs

### ISSUE THREAD

**Issue by ElDavoo** [jepbura/gaganode#4]
```
apphub-linux does not exist
/myApp/gaganode_install.sh: line 25: sudo: command not found
/myApp/gaganode_install.sh: line 31: sudo: command not found
/myApp/gaganode_install.sh: line 32: sudo: command not found
/myApp/gaganode_install.sh: line 38: sudo: command not found

```

**Comment by jepbura** [comment]
In new version you must enter DOWNLOADLINK, FILENAME, TOKEN not just TOKEN.
Please read the [README.md](https://github.com/jepbura/gaganode/blob/master/README.md) file.

**Comment by ElDavoo** [comment]
> In new version you must enter DOWNLOADLINK, FILENAME, TOKEN not just TOKEN. Please read the [README.md](https://github.com/jepbura/gaganode/blob/master/README.md) file.

That's not the problem, is sudo that needs to be installed in the container
The container itself can also be rebased to 24.04 since it's out

**Comment by engageub** [comment]
Yes, I see the same error. You probably have to resolve sudo from the shell script as it is not installed by default.
You can go inside the container using "docker exec" command and try to run sudo command manually. 


```
cpu_arch=aarch64
DOWNLOADLINK=https://assets.coreservice.io/public/package/61/app-market-gaga-pro/1.0.4/app-market-gaga-pro-1_0_4.tar.gz
FILENAME=apphub-linux-arm64.tar.gz
TOKEN=------------------------------------
apphub-linux does not exist
/myApp/gaganode_install.sh: line 25: sudo: command not found
/myApp/gaganode_install.sh: line 31: sudo: command not found
/myApp/gaganode_install.sh: line 32: sudo: command not found
/myApp/gaganode_install.sh: line 38: sudo: command not found
```

Thank you

**Comment by jepbura** [comment]
@ElDavoo @engageub 
You can check again now.
